language: node_js
node_js:
  - "0.10"

install:
  - ./script/setup
  - gem install scss-lint --no-ri --version "=0.24.0"

script:
  - travis_retry ./script/travis_script.sh

after_success:
  - ./script/travis_artifacts.sh
